#ifndef CESCAPE_TYPE_H
#define CESCAPE_TYPE_H

enum CEscapeColor {
  CESCAPE_COLOR_BLACK  =0,
  CESCAPE_COLOR_RED    =1,
  CESCAPE_COLOR_GREEN  =2,
  CESCAPE_COLOR_YELLOW =3,
  CESCAPE_COLOR_BLUE   =4,
  CESCAPE_COLOR_MAGENTA=5,
  CESCAPE_COLOR_CYAN   =6,
  CESCAPE_COLOR_WHITE  =7,

  CESCAPE_COLOR_BG     =8,
  CESCAPE_COLOR_FG     =9,

  CESCAPE_COLOR_DIM=(1<<8),

  CESCAPE_COLOR_DIM_BLACK  =(CESCAPE_COLOR_DIM | CESCAPE_COLOR_BLACK),
  CESCAPE_COLOR_DIM_RED    =(CESCAPE_COLOR_DIM | CESCAPE_COLOR_RED),
  CESCAPE_COLOR_DIM_GREEN  =(CESCAPE_COLOR_DIM | CESCAPE_COLOR_GREEN),
  CESCAPE_COLOR_DIM_YELLOW =(CESCAPE_COLOR_DIM | CESCAPE_COLOR_YELLOW),
  CESCAPE_COLOR_DIM_BLUE   =(CESCAPE_COLOR_DIM | CESCAPE_COLOR_BLUE),
  CESCAPE_COLOR_DIM_MAGENTA=(CESCAPE_COLOR_DIM | CESCAPE_COLOR_MAGENTA),
  CESCAPE_COLOR_DIM_CYAN   =(CESCAPE_COLOR_DIM | CESCAPE_COLOR_CYAN),
  CESCAPE_COLOR_DIM_WHITE  =(CESCAPE_COLOR_DIM | CESCAPE_COLOR_WHITE)
};

#endif
